### ISSUE TITLE
theme 404 page

### ISSUE THREAD

**Issue by pvhee** [marzeelabs/compraaospequenos#15]
We will likely run into many 404 since the quality of the data from the gdoc is poor (many broken links). 

Therefore, the 404 page should probably be styled and/or link to existing content.

Example: https://compraaospequenos.netlify.com/hdhsjhdjhsad

![image](https://user-images.githubusercontent.com/119355/77986994-19d55280-7375-11ea-9e1c-611dfeceea2b.png)

**Comment by Quicksaver** [comment]
A proper 404 is always a good idea of course, but I don't see how it will help with the links coming from the spreadsheet, those are external and will always be absolute. That 404 is for internal links only.

**Comment by pvhee** [comment]
Clicking around on a few (supposedly external) links I did get 404. I guess it depends whether or not the url is well formed, often it is not so will revert to internal link.

**Comment by pdsdesign** [comment]
Done a pass on this here https://www.figma.com/file/ILDhuzFFvyqKijeVjJqHRC/compro_aos_pequenos?node-id=248%3A0
