### ISSUE TITLE
Articles page

### ISSUE THREAD

**Issue by AnaRossetto** [marzeelabs/compraaospequenos#17]
A space for dedicated content for small businesses. 
The idea is to have a back-office so they can add content - articles and videos.

How could we implement a back-office here? Should we go for CMS? or do we have other easier/fastest (but still reliable) option?

- [x] implement Netlify CMS 
- [x] page for list of articles 
- [x] articles pages

**Comment by AnaRossetto** [comment]
@pvhee they sent this as an example - https://cuidedopequenonegocio.com.br/fique-por-dentro 
What do you need from me to have this ready for styling work?

**Comment by pvhee** [comment]
@AnaRossetto  articles structure and NetlifyCMS conf are now implemented:

- https://5e9e8a8251870400074d6ed6--compraaospequenos.netlify.app/articles/ & click through to article page
- https://5e9e8a8251870400074d6ed6--compraaospequenos.netlify.app/admin <-- I've sent you an invite to edit content. Note that you cannot see existing content as this is pulled from the `master` branch and this PR is not yet merged. If @Quicksaver agrees, we can merge in changes to production whilst @pdsdesign & team work on front-end for this

**Comment by pvhee** [comment]
Note that articles have:

- title
- date
- featured image
- tags (multiple)
- body content

**Comment by pdsdesign** [comment]
@AnaRossetto @pvhee 
I've done a quick pass on this here https://www.figma.com/file/ILDhuzFFvyqKijeVjJqHRC/compro_aos_pequenos?node-id=0%3A1

**Comment by AnaRossetto** [comment]
@pvhee @pdsdesign they want to name this section as "Dicas e Ferramentas"

**Comment by AnaRossetto** [comment]
@pdsdesign the design to be implemented 
[articles.pdf](https://github.com/marzeelabs/compraaospequenos/files/4528517/articles.pdf)
[articles full 2.pdf](https://github.com/marzeelabs/compraaospequenos/files/4528518/articles.full.2.pdf)
