### ISSUE TITLE
Media Coverage slideshow 

### ISSUE THREAD

**Issue by AnaRossetto** [marzeelabs/compraaospequenos#18]
As expected they want a slideshow to share the newspapers that have talked about the movement. Maybe there’s a Gatsby plugin for this? Do you know of any?

**Comment by AnaRossetto** [comment]
@Quicksaver do you know how we could implement this? I remember @pvhee saying about Gatsby having something for this. 

I was thinking to have the metatag share image and the title of the news piece on the slide show. 
This is important for them so users can see the credibility of the movement. 

The list of links to go to this slide show is the following:
- https://www.publico.pt/2020/03/19/local/noticia/compraaospequenos-iniciativa-apoiar-negocios-1908501
- https://observador.pt/opiniao/a-economia-nao-pode-morrer-e-vital-apoiar-os-pequenos-negocios/
- https://www.jornaldenegocios.pt/economia/coronavirus/detalhe/menos-hub-lanca-movimento-compraaospequenos?ref=HP_DestaquesPrincipais
- https://jornaleconomico.sapo.pt/noticias/startup-cria-plataforma-para-apoiar-pequenos-negocios-e-importante-reduzir-os-custos-fixos-e-continuar-a-vender-561952
- https://www.dinheirovivo.pt/fazedores/nasceu-plataforma-para-ajudar-pequenos-negocios-de-portugal/

**Comment by Quicksaver** [comment]
I don't know off the top of my head the how, but should be easy. I'd probably save the images and texts locally as well, rather than fetching from those links on every build.
