### ISSUE TITLE
Spreadsheet organization

### ISSUE THREAD

**Issue by Quicksaver** [marzeelabs/compraaospequenos#6]
If Menos are handling the spreadsheet, they should take some care to organize it and add data in a structured way so that the site can reliably read from it.

- [x] locations need to be cleaned up
Some entries (i.e. Insurtek) should only have Todo o País, not any of the others

- [x] social, site, and contact columns need organization, it's impossible to show as it is, suggestion:

- column for social sites, all links must be valid (invalid will not be shown in card), separate with commas
supported (they can add others to the spreadsheet if they want already, they just won't appear in the website until we add support): facebook, instagram
e.g.:
  - `https://www.facebook.com/marzeelabs`
  - `https://www.facebook.com/marzeelabs , https://www.instagram.com/menoshub/`

- column for website (no social sites here), single link, must be valid (we don't validate)
e.g.:
  - `https://marzeelabs.org`

- column for emails, separate with commas, must be valid (we don't validate)
e.g.:
  - `info@marzeelabs.org`
  - `info@marzeelabs.org , hi@menoshub.com`

- column for telephone, separate with commas, can be number plus time/location information (we don't validate)
no spaces in number, we'll take care of those
e.g.:
  - `911705510`
  - `911705510 (9h-12h)`
  - `911705510 (9h-12h) , 911705510`
  - `911705510 (Lisboa) , 911705510 (Porto - 9h-12h)`

**Comment by AnaRossetto** [comment]
@Quicksaver sent a message to them.

**Comment by pvhee** [comment]
👍 this is crucial for this site to work correctly and not annoy users trying to browse the listing

**Comment by AnaRossetto** [comment]
@pvhee @Quicksaver this is already updated by menos team!
