### ISSUE TITLE
How should we handle filtering for "Todo o País"?

### ISSUE THREAD

**Issue by Quicksaver** [marzeelabs/compraaospequenos#7]
Currently it's just another filter as if it were another location, meaning if you filter for "Faro" those with "Todo o País" do not appear, and vice-versa.

If we make it so that filtering for "Faro" also shows those shops with "Todo o País", it's going to take some magic, I'd suggest for after MVP.

**Comment by AnaRossetto** [comment]
@Quicksaver let's first to decide how we are going to tackle the spreadsheet structure. Maybe we find a solution for this too!

**Comment by pvhee** [comment]
I _think_ this is sorted, so closing
